// Generated by CoffeeScript 1.6.3
afterEach(function(done) {
  $("#sandbox").html('');
  dermis.router.base('');
  dermis.router.clear();
  return $(document).ready(function() {
    return done();
  });
});
